### ISSUE TITLE
Some errors maybe related to Pytorch version

### ISSUE THREAD

**Issue by elfeffe** [cuicaihao/fast_neural_style#1]
I'm using Pytorch 1.6.0 (got it running conda install pytorch torchvision -c soumith), and I get this

	Unexpected running stats buffer(s) "in1.running_mean" and "in1.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.

How to solve the issue? Do I have to downgrade Pytorch?

**Comment by cuicaihao** [comment]
> I'm using Pytorch 1.6.0 (got it running conda install pytorch torchvision -c soumith), and I get this
> 
> ```
> Unexpected running stats buffer(s) "in1.running_mean" and "in1.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
> ```
> 
> How to solve the issue? Do I have to downgrade Pytorch?

Hi there, I updated the code to fit the PyTorch 1.7.0 with python 3.8.3. So I will close this issue now. 
I will update the blog later. cheers.
